### ISSUE TITLE
Pack a box to a certain volume?

### ISSUE THREAD

**Issue by seikoh00** [dvdoug/BoxPacker#217] opened 2020-12-29 21:20 UTC
Does this package have a way to pack a box up to a certain volume or volume percentage given the inner dimensions of a box? For example, I have a box with inner dimensions (inches) of 12x10x8 and I would like to fill it up to 80% of it's volume capacity. I would know this percentage ahead of time and it could be variable per box.

Looking through the code it doesn't seem explicitly available, but there are methods available (usedVolume, volumeUtilization) where maybe this could be done in a round about way?

**Comment by dvdoug** [comment] 2020-12-31 18:30
Dupe of https://github.com/dvdoug/BoxPacker/discussions/216

**Closed by dvdoug** 2020-12-31 18:30 UTC
